author: Dmitriy Sevkovych
url: https://varsandnumbers.com
locale: de-DE
email: info@varsandnumbers.com
personal_email: d.sevkovych@varsandnumbers.com
title_tab: Vars&Numbers
title: 'Vars <br> & <br> Numbers'
subtitle: 'Mathematics? Software? Both!'
description: Hi, I am a freelance software developer with a M.Sc. degree in mathematics. My focus lies basically on everything that deals with variables and numbers, namely full-stack web development, data science and numerical simulation. And I like digital design.
keywords: Mathematics,IT,Software,Development,Web,Learning,Data,Simulation,Digital,Design

gems:
  - jekyll-babel

exclude:
  - .gitignore
  - .htpasswd
  - .htaccess
  - node_modules
  - package.json
  - package-lock.json
  - gulpfile.js
  - assets/img_raw
  - assets/sass
