gems:
  - jekyll-babel

exclude:
  - .gitignore
  - .htpasswd
  - .htaccess
  - node_modules
  - package.json
  - package-lock.json
  - gulpfile.js
  - assets/img_raw
  - assets/sass
  - assets/css/*.css.map
